version: 2
jobs:
  checkout:
    docker:
      - image: circleci/node:9.4
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  ci:
    docker:
      - image: circleci/node:9.4
    steps:
      - attach_workspace:
          at: .
      - run: yarn ci
  release:
    docker:
      - image: circleci/node:9.4
    steps:
      - attach_workspace:
          at: .
      - run: yarn release ${CIRCLE_TAG}
workflows:
  version: 2
  ci-and-release:
    jobs:
      - checkout:
          filters:
            tags:
              only: /.*/
      - ci:
          requires:
            - checkout
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - ci
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9](\.[0-9]){2}.*$/
